const PreSolicitud = [
    {
      CodVendedor: 6174,
      NomVendedor: 'Baldassarre Belen',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-02-12T15:30:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 855,
      NomVendedor: 'Braga Facundo',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-04-26T13:36:00.000Z',
      FechaBajaVendedor: '2018-11-23T00:00:00.000Z',
      Ingresadas: 6,
      VentasMP: null,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 2,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 417,
      NomVendedor: 'Caamaño Pablo',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-08-15T16:12:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 6,
      VentasMP: null,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 11,
      MesAnt2: 2,
      MesAnt3: 9,
      Anuladas: 1,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 273,
      NomVendedor: 'Carranza Nicolas',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-06-08T09:51:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6190,
      NomVendedor: 'Detrona Martin',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-15T16:13:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 769,
      NomVendedor: 'Ibarra Nazarena',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-03-22T16:38:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 8,
      VentasMP: null,
      Objetivo: null,
      Produccion: 8,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 6,
      MesAnt2: 5,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 8,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6172,
      NomVendedor: 'Lara Luz',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-02-11T17:57:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 290,
      NomVendedor: 'Luna Julio',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-06-08T09:55:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 8,
      VentasMP: null,
      Objetivo: null,
      Produccion: 10,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 10,
      MesAnt2: 6,
      MesAnt3: 2,
      Anuladas: null,
      PrecioA: 8,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6061,
      NomVendedor: 'Pinto Nadia',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-10-24T18:11:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 6,
      MesAnt2: 6,
      MesAnt3: 3,
      Anuladas: 1,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 196,
      NomVendedor: 'Quiroga Jackeline',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-03-02T12:52:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 2,
      MesAnt3: 6,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 820,
      NomVendedor: 'Sali Noe Kevin',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-04-12T12:34:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: 9,
      MesAnt3: 12,
      Anuladas: 1,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6173,
      NomVendedor: 'Torres Gabriel',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-02-11T18:02:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 7,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6115,
      NomVendedor: 'Trintinaglia Karla',
      CodSucursal: 31,
      NomSucursal: 'ADN av belgrano',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-11-20T16:21:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 4,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 6,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 276,
      NomVendedor: 'Acevedo Gisela',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-06-08T09:51:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 558,
      NomVendedor: 'Bogado Ignacio',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-11-16T16:17:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 8,
      VentasMP: null,
      Objetivo: null,
      Produccion: 12,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 7,
      MesAnt2: 3,
      MesAnt3: 8,
      Anuladas: null,
      PrecioA: 8,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6191,
      NomVendedor: 'Carreras Roberto',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-15T16:14:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 511,
      NomVendedor: 'Contreras Antonio',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-10-12T11:29:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 11,
      VentasMP: null,
      Objetivo: null,
      Produccion: 11,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: 1,
      C8: 1,
      C9: null,
      MesAnt: 7,
      MesAnt2: 1,
      MesAnt3: 6,
      Anuladas: 1,
      PrecioA: 11,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6134,
      NomVendedor: 'Corvalan Jose',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-12-10T16:53:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: 3,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6200,
      NomVendedor: 'Cricenti Gian Franco',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-26T17:09:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6201,
      NomVendedor: 'Deamelio Damian',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-26T17:09:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6193,
      NomVendedor: 'Deamelio Lucas ',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-19T17:19:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6197,
      NomVendedor: 'Dornell Diego',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-20T18:15:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 5,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: 1,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 5,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6194,
      NomVendedor: 'Espindola Leonel ',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-19T17:19:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6116,
      NomVendedor: 'Fortezza Nazarena',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-11-20T16:38:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: 1,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6171,
      NomVendedor: 'Maidana Ana',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-02-08T16:50:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 10,
      VentasMP: null,
      Objetivo: null,
      Produccion: 9,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 2,
      PrecioA: 10,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6192,
      NomVendedor: 'Maiolino Enzo',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-18T18:04:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 698,
      NomVendedor: 'Marquez Rocio ',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-02-15T15:43:00.000Z',
      FechaBajaVendedor: '2018-11-23T00:00:00.000Z',
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: 1,
      C9: null,
      MesAnt: 6,
      MesAnt2: 1,
      MesAnt3: 3,
      Anuladas: 1,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6202,
      NomVendedor: 'Medina Facundo ',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-26T17:10:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6196,
      NomVendedor: 'Molina Maria Jose',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-20T18:10:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 357,
      NomVendedor: 'Peralta Yanet',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-07-11T12:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 8,
      VentasMP: null,
      Objetivo: null,
      Produccion: 9,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 4,
      MesAnt2: 3,
      MesAnt3: 1,
      Anuladas: 1,
      PrecioA: 8,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6198,
      NomVendedor: 'Piroca Martin',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-20T18:16:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6189,
      NomVendedor: 'Riquelme Irene',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-15T16:13:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 6,
      VentasMP: null,
      Objetivo: null,
      Produccion: 4,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 216,
      NomVendedor: 'Rodriguez Cristian',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-03-31T18:22:00.000Z',
      FechaBajaVendedor: '2018-11-23T00:00:00.000Z',
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: 1,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6195,
      NomVendedor: 'Rodriguez Jose ',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2019-03-19T17:20:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 235,
      NomVendedor: 'Romero Estefania',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2017-04-27T17:44:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 5,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 7,
      MesAnt2: 1,
      MesAnt3: 3,
      Anuladas: 1,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 907,
      NomVendedor: 'Urbieta Alejandro',
      CodSucursal: 20,
      NomSucursal: 'ADN Av de Los Incas',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2018-06-13T15:53:00.000Z',
      FechaBajaVendedor: '2018-11-23T00:00:00.000Z',
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6184,
      NomVendedor: 'Chentorbi Devora',
      CodSucursal: 308,
      NomSucursal: 'Benesur SRL',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-03-06T16:53:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6182,
      NomVendedor: 'Dasis Daiana',
      CodSucursal: 308,
      NomSucursal: 'Benesur SRL',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-03-06T16:52:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 350,
      NomVendedor: 'Ibañez Pablo',
      CodSucursal: 308,
      NomSucursal: 'Benesur SRL',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-07-06T17:40:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6183,
      NomVendedor: 'Ibarra Julieta',
      CodSucursal: 308,
      NomSucursal: 'Benesur SRL',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-03-06T16:53:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 547,
      NomVendedor: 'Mainardi Leandro',
      CodSucursal: 308,
      NomSucursal: 'Benesur SRL',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-11-01T11:46:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 2,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6150,
      NomVendedor: 'Alegre Nicolas (Castro)',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-01-03T13:38:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 6,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 8,
      C2: 1,
      C3: 5,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 6,
      MesAnt2: 9,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 701,
      NomVendedor: 'Castro Fernando',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-02-16T16:27:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: 3,
      Produccion: null,
      C2: null,
      C3: 4,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 2,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6148,
      NomVendedor: 'Fernandez Pablo',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-01-03T13:33:00.000Z',
      FechaBajaVendedor: '2019-03-15T00:00:00.000Z',
      Ingresadas: null,
      VentasMP: null,
      Objetivo: 5,
      Produccion: null,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 2,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6165,
      NomVendedor: 'Filardi Ramiro',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-06T11:13:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 3,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6166,
      NomVendedor: 'Gazi Juan Manuel',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-06T11:16:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 2,
      C2: null,
      C3: 2,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6042,
      NomVendedor: 'Rodriguez Camilo',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-10-10T18:11:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 8,
      VentasMP: null,
      Objetivo: 5,
      Produccion: null,
      C2: null,
      C3: 7,
      C4: null,
      C5: null,
      C6: 2,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 4,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: 8,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6164,
      NomVendedor: 'Salvatierra Christian',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-06T11:12:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: 5,
      Produccion: null,
      C2: null,
      C3: 2,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 859,
      NomVendedor: 'Vazquez Victor Hugo',
      CodSucursal: 46,
      NomSucursal: 'Castro Fernando',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-05-02T11:12:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 10,
      VentasMP: null,
      Objetivo: 7,
      Produccion: 5,
      C2: null,
      C3: 7,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 6,
      MesAnt2: 9,
      MesAnt3: 5,
      Anuladas: null,
      PrecioA: 10,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6108,
      NomVendedor: 'Joel Maestu',
      CodSucursal: 304,
      NomSucursal: 'Christian Aguirre',
      CodGerente: 103,
      NomGerente: 'Alan Almanza',
      FechaAltaVendedor: '2018-11-12T15:30:00.000Z',
      FechaBajaVendedor: '2019-01-31T00:00:00.000Z',
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 1,
      MesAnt3: 3,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6080,
      NomVendedor: 'Artica Katherine',
      CodSucursal: 13,
      NomSucursal: 'Colangelo Sebastian',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-11-01T15:58:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: 1,
      C6: null,
      C7: 1,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: 5,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 125,
      NomVendedor: 'Colangelo Sebastian',
      CodSucursal: 13,
      NomSucursal: 'Colangelo Sebastian',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2016-03-01T15:53:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 4,
      C2: null,
      C3: 2,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 4,
      MesAnt2: 2,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6167,
      NomVendedor: 'Poliotti Vanina',
      CodSucursal: 13,
      NomSucursal: 'Colangelo Sebastian',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-06T16:41:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: 5,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6119,
      NomVendedor: 'Rodriguez Hugo',
      CodSucursal: 13,
      NomSucursal: 'Colangelo Sebastian',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-11-22T11:21:00.000Z',
      FechaBajaVendedor: '2019-03-29T00:00:00.000Z',
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 1,
      C2: null,
      C3: 4,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 4,
      MesAnt2: 1,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6181,
      NomVendedor: 'Rubini Gaston',
      CodSucursal: 13,
      NomSucursal: 'Colangelo Sebastian',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-28T17:02:00.000Z',
      FechaBajaVendedor: '2019-03-29T00:00:00.000Z',
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6079,
      NomVendedor: 'Zamora Leonel',
      CodSucursal: 13,
      NomSucursal: 'Colangelo Sebastian',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-11-01T12:06:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 1,
      C2: null,
      C3: 2,
      C4: null,
      C5: null,
      C6: 1,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 1,
      MesAnt3: 5,
      Anuladas: 1,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6199,
      NomVendedor: 'Gomez Galarza',
      CodSucursal: 60,
      NomSucursal: 'Enzo Galarza II',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-03-25T20:04:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6028,
      NomVendedor: 'Rey Sergio',
      CodSucursal: 60,
      NomSucursal: 'Enzo Galarza II',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-09-25T16:22:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: 2,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6142,
      NomVendedor: 'Cipriani Nicolas',
      CodSucursal: 303,
      NomSucursal: 'Federico Feresin',
      CodGerente: 103,
      NomGerente: 'Alan Almanza',
      FechaAltaVendedor: '2018-12-21T16:08:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 1,
      C2: null,
      C3: 2,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: 2,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6122,
      NomVendedor: 'Feresin Federico',
      CodSucursal: 303,
      NomSucursal: 'Federico Feresin',
      CodGerente: 103,
      NomGerente: 'Alan Almanza',
      FechaAltaVendedor: '2018-11-26T16:12:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: 2,
      MesAnt3: 1,
      Anuladas: 1,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6151,
      NomVendedor: 'Marquiegui Daniel',
      CodSucursal: 303,
      NomSucursal: 'Federico Feresin',
      CodGerente: 103,
      NomGerente: 'Alan Almanza',
      FechaAltaVendedor: '2019-01-03T14:31:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 2,
      C2: null,
      C3: 2,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: 2,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6135,
      NomVendedor: 'Navarro Fernando Franco',
      CodSucursal: 303,
      NomSucursal: 'Federico Feresin',
      CodGerente: 103,
      NomGerente: 'Alan Almanza',
      FechaAltaVendedor: '2018-12-11T13:44:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: 5,
      Produccion: 3,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 4,
      MesAnt3: 1,
      Anuladas: 1,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6099,
      NomVendedor: 'Trivilin Flavio',
      CodSucursal: 303,
      NomSucursal: 'Federico Feresin',
      CodGerente: 103,
      NomGerente: 'Alan Almanza',
      FechaAltaVendedor: '2018-11-12T15:26:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: 1,
      Objetivo: 5,
      Produccion: null,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 4,
      MesAnt2: 5,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 0,
      Crucescoring: null,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 5975,
      NomVendedor: 'Alcaraz Valeria',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-08-10T16:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 7,
      VentasMP: null,
      Objetivo: null,
      Produccion: 7,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 5,
      MesAnt2: 5,
      MesAnt3: 6,
      Anuladas: null,
      PrecioA: 7,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6187,
      NomVendedor: 'Alegre David',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-03-13T12:47:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 555,
      NomVendedor: 'Alfaro Diego',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-11-13T16:02:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 10,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 12,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 8,
      MesAnt3: 8,
      Anuladas: 1,
      PrecioA: 10,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6141,
      NomVendedor: 'Ardiles Sebastian',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-12-20T15:19:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: 2,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 2,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6060,
      NomVendedor: 'Cristaldo Maximiliano',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-10-24T17:13:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 8,
      VentasMP: null,
      Objetivo: null,
      Produccion: 9,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 10,
      MesAnt2: 9,
      MesAnt3: 3,
      Anuladas: 1,
      PrecioA: 8,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6120,
      NomVendedor: 'Delfino Pablo ',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-11-22T13:28:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 2,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 298,
      NomVendedor: 'Figueroa Mariana',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-06-09T10:06:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 5,
      VentasMP: 3,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 9,
      MesAnt2: 15,
      MesAnt3: 11,
      Anuladas: null,
      PrecioA: 5,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 832,
      NomVendedor: 'Garcia Paloma',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-04-17T17:55:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 4,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: 2,
      MesAnt3: 8,
      Anuladas: null,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6176,
      NomVendedor: 'Gatti Bruno',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-13T13:36:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 2,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 2,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 2
    },
    {
      CodVendedor: 5989,
      NomVendedor: 'Gomez Brian ',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-08-29T16:08:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: 1,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 2,
      MesAnt3: 8,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6132,
      NomVendedor: 'Heredia Roman',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-12-05T15:40:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: 4,
      MesAnt3: 2,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 297,
      NomVendedor: 'Isasi Enrique',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-06-09T10:05:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: null,
      MesAnt3: 5,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 938,
      NomVendedor: 'Jeskiewicz Kevin ',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-07-13T13:42:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 6,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 11,
      MesAnt2: 13,
      MesAnt3: 9,
      Anuladas: 2,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 2
    },
    {
      CodVendedor: 6083,
      NomVendedor: 'Kotik Agustina',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-11-02T13:03:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 7,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 7,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 9,
      MesAnt2: 4,
      MesAnt3: 3,
      Anuladas: 1,
      PrecioA: 7,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 3,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6178,
      NomVendedor: 'Leucci Jonathan',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-14T17:04:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 4,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 300,
      NomVendedor: 'Lusardi Facundo',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-06-09T10:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 2,
      MesAnt3: 3,
      Anuladas: 1,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 533,
      NomVendedor: 'Martinez Ezequiel Sebastian',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-10-25T17:15:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 5,
      MesAnt2: 7,
      MesAnt3: 2,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6057,
      NomVendedor: 'Morini Joel ',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-10-24T13:27:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 6,
      VentasMP: null,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 5,
      MesAnt2: 2,
      MesAnt3: 3,
      Anuladas: null,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 554,
      NomVendedor: 'Mujica Jonathan',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-11-13T15:31:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: 1,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: 1,
      MesAnt3: 2,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 301,
      NomVendedor: 'Opresnik Federico',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-06-09T10:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 12,
      VentasMP: null,
      Objetivo: null,
      Produccion: 14,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: 1,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 20,
      MesAnt2: 10,
      MesAnt3: 3,
      Anuladas: 2,
      PrecioA: 12,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 2
    },
    {
      CodVendedor: 628,
      NomVendedor: 'Otaola Emiliano',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-01-15T17:26:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 6,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: 5,
      MesAnt3: 6,
      Anuladas: 2,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 2
    },
    {
      CodVendedor: 6186,
      NomVendedor: 'Paniagua Daniel',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-03-12T15:00:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 5,
      VentasMP: null,
      Objetivo: null,
      Produccion: 5,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 5,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6026,
      NomVendedor: 'Piccardo Bruno',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-09-20T15:29:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: 1,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 14,
      MesAnt2: 14,
      MesAnt3: 8,
      Anuladas: 1,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6006,
      NomVendedor: 'Recalde Facundo',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-09-07T16:52:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 11,
      VentasMP: null,
      Objetivo: null,
      Produccion: 12,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 8,
      MesAnt2: 5,
      MesAnt3: 2,
      Anuladas: 1,
      PrecioA: 11,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 302,
      NomVendedor: 'Rodriguez Laura',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-06-09T10:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 13,
      VentasMP: 2,
      Objetivo: null,
      Produccion: 13,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 5,
      MesAnt2: 4,
      MesAnt3: 7,
      Anuladas: null,
      PrecioA: 13,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6049,
      NomVendedor: 'Sarricueta Federico',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-10-17T12:39:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 8,
      VentasMP: null,
      Objetivo: null,
      Produccion: 8,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 8,
      MesAnt2: 6,
      MesAnt3: 5,
      Anuladas: null,
      PrecioA: 8,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6185,
      NomVendedor: 'Silveyra Lorenzo',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-03-11T13:10:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6114,
      NomVendedor: 'Spinelli Juan Gabriel',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-11-20T12:23:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 4,
      C2: null,
      C3: null,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 6,
      MesAnt2: 7,
      MesAnt3: 1,
      Anuladas: 2,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 2
    },
    {
      CodVendedor: 6140,
      NomVendedor: 'Szerstiuk Santiago',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-12-18T13:50:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 1,
      MesAnt3: 3,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 304,
      NomVendedor: 'Velazquez Debora',
      CodSucursal: 29,
      NomSucursal: 'Hirsch Gaston',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-06-09T10:08:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 6,
      MesAnt3: 3,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 771,
      NomVendedor: 'Carril Camila',
      CodSucursal: 51,
      NomSucursal: 'Icolombo',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-03-22T17:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: 1,
      Anuladas: 1,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6179,
      NomVendedor: 'Michia Maximiliano',
      CodSucursal: 51,
      NomSucursal: 'Icolombo',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-22T18:05:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 772,
      NomVendedor: 'Zamora Leandro',
      CodSucursal: 51,
      NomSucursal: 'Icolombo',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-03-22T17:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 10,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 8,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 12,
      MesAnt2: 7,
      MesAnt3: 7,
      Anuladas: 1,
      PrecioA: 10,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 462,
      NomVendedor: 'Alegre Nicolas Ezequiel (Liderazgo)',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2017-09-18T12:29:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 5,
      MesAnt2: 10,
      MesAnt3: 5,
      Anuladas: 2,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 2
    },
    {
      CodVendedor: 6188,
      NomVendedor: 'Chavez Alexis',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2019-03-13T16:48:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 3,
      VentasMP: null,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 3,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 606,
      NomVendedor: 'Chazarreta Ramiro',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2017-12-26T14:57:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: 1,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 1,
      MesAnt3: 4,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6203,
      NomVendedor: 'Cura Matias ',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2019-03-29T13:33:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: 1,
      C9: null,
      MesAnt: null,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 5991,
      NomVendedor: 'Decima Carolina ',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2018-08-30T12:43:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 3,
      MesAnt3: 2,
      Anuladas: 3,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: 2
    },
    {
      CodVendedor: 452,
      NomVendedor: 'Gorosito Ivan',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2017-09-11T18:36:00.000Z',
      FechaBajaVendedor: '2017-12-31T00:00:00.000Z',
      Ingresadas: 10,
      VentasMP: null,
      Objetivo: null,
      Produccion: 10,
      C2: null,
      C3: 3,
      C4: null,
      C5: 1,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 9,
      MesAnt2: 9,
      MesAnt3: 7,
      Anuladas: null,
      PrecioA: 10,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6055,
      NomVendedor: 'Juarez LIDER Eugenia',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2018-10-23T15:06:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 13,
      VentasMP: null,
      Objetivo: null,
      Produccion: 7,
      C2: 1,
      C3: 1,
      C4: null,
      C5: 2,
      C6: null,
      C7: 1,
      C8: null,
      C9: null,
      MesAnt: 12,
      MesAnt2: 12,
      MesAnt3: 6,
      Anuladas: 1,
      PrecioA: 13,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6068,
      NomVendedor: 'Mendoza Leonardo',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2018-10-29T09:16:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 5,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 2,
      MesAnt3: 2,
      Anuladas: null,
      PrecioA: 5,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6154,
      NomVendedor: 'Moreno Alan',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2019-01-07T15:40:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 7,
      VentasMP: null,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 3,
      MesAnt2: 7,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 7,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 541,
      NomVendedor: 'Ortiz Gonzalo',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2017-10-30T16:40:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 6,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: 4,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: 1,
      C9: null,
      MesAnt: 4,
      MesAnt2: 9,
      MesAnt3: 3,
      Anuladas: 1,
      PrecioA: 6,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6067,
      NomVendedor: 'Salazar Dayana',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2018-10-29T08:59:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 5,
      VentasMP: 1,
      Objetivo: null,
      Produccion: 2,
      C2: null,
      C3: 3,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 2,
      MesAnt2: 2,
      MesAnt3: 3,
      Anuladas: null,
      PrecioA: 5,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6111,
      NomVendedor: 'Salinas German',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2018-11-12T18:02:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 2,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 5,
      MesAnt2: null,
      MesAnt3: 1,
      Anuladas: null,
      PrecioA: 2,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 551,
      NomVendedor: 'Torres Franco',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2017-11-08T15:31:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 3,
      C2: null,
      C3: 1,
      C4: null,
      C5: null,
      C6: 1,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 4,
      MesAnt2: 7,
      MesAnt3: 3,
      Anuladas: null,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 2,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6157,
      NomVendedor: 'Zalazar Dayana',
      CodSucursal: 38,
      NomSucursal: 'Liderazgo Automotriz',
      CodGerente: 15,
      NomGerente: 'Liderazgo Automotriz',
      FechaAltaVendedor: '2019-01-08T15:17:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 1,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 151,
      NomVendedor: 'Medina Sergio',
      CodSucursal: 18,
      NomSucursal: 'Medina Sergio',
      CodGerente: 11,
      NomGerente: 'ADN',
      FechaAltaVendedor: '2016-09-12T13:11:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 13,
      VentasMP: null,
      Objetivo: null,
      Produccion: 8,
      C2: null,
      C3: 5,
      C4: null,
      C5: null,
      C6: null,
      C7: 1,
      C8: null,
      C9: null,
      MesAnt: 10,
      MesAnt2: 9,
      MesAnt3: 5,
      Anuladas: 1,
      PrecioA: 13,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: 1,
      Zona: 1,
      NombreZona: 'Buenos Aires',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 924,
      NomVendedor: 'Corbalan Adriana',
      CodSucursal: 282,
      NomSucursal: 'Walter Villafañe',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-07-06T10:07:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: null,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 1,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: 1
    },
    {
      CodVendedor: 6089,
      NomVendedor: 'Rodriguez Facundo',
      CodSucursal: 282,
      NomSucursal: 'Walter Villafañe',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-11-09T15:23:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 1,
      VentasMP: null,
      Objetivo: null,
      Produccion: 1,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: null,
      MesAnt2: 2,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 1,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6170,
      NomVendedor: 'Romero Gabriel',
      CodSucursal: 282,
      NomSucursal: 'Walter Villafañe',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2019-02-08T11:53:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 8,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 6,
      MesAnt2: null,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 6050,
      NomVendedor: 'Ruiz Karen',
      CodSucursal: 282,
      NomSucursal: 'Walter Villafañe',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2018-10-18T09:39:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: null,
      VentasMP: 1,
      Objetivo: null,
      Produccion: null,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 1,
      MesAnt2: 2,
      MesAnt3: null,
      Anuladas: null,
      PrecioA: null,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: null,
      AnuladaRechazada: null
    },
    {
      CodVendedor: 315,
      NomVendedor: 'Walter Villafañe',
      CodSucursal: 282,
      NomSucursal: 'Walter Villafañe',
      CodGerente: 3,
      NomGerente: 'Bevacqua Ricardo',
      FechaAltaVendedor: '2017-06-15T10:39:00.000Z',
      FechaBajaVendedor: null,
      Ingresadas: 4,
      VentasMP: null,
      Objetivo: null,
      Produccion: 6,
      C2: null,
      C3: null,
      C4: null,
      C5: null,
      C6: null,
      C7: null,
      C8: null,
      C9: null,
      MesAnt: 5,
      MesAnt2: 4,
      MesAnt3: null,
      Anuladas: 1,
      PrecioA: 4,
      PrecioB: null,
      EsMiniEmprendedor: 1,
      Crucescoring: null,
      Zona: 2,
      NombreZona: 'Mar del Plata',
      AnuladaTresYSiete: 1,
      AnuladaRechazada: null
    }
  ]
export default PreSolicitud